{% set name = "sampledb" %}
{% set version = "0.1.5" %}
{% set sha256 = "5d77609951548bed4359a3f5fe3228b6d5b2f608fc5e2b5fbc935927a8ff91f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [not py36]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - xlrd
    - xlsxwriter
    - pymongo
    - pandas
    - jsonschema
    - xonsh
    - pyyaml
    # Note that the qr writer requires latex and I don't want to get into
    # cf tex distributions

test:
  imports:
    - sampledb
    - sampledb.databasesearcher
    - sampledb.datapublisher

about:
  home: https://github.com/diffpy/sampledb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A DB for sample and synthesis metadata information'

  doc_url: http://www.diffpy.org/sampledb/
  dev_url: https://github.com/diffpy/sampledb

extra:
  recipe-maintainers:
    - CJ-Wright
    - justcalamari
