travis:
  secure:
    BINSTAR_TOKEN: cf9Nc0beC1lq842n+aYZzox31Ml9pWKaIycFUu5aHoAE6aXYYOvfOdeDFEsp7onOwy43rb3D3YLhAG5+YtgvKGUPYexYpCqFhaNWdmKRFrx8+npXUoZR7bYe+hI2/MDQrsRVo92oz6Tpa/UE9QPWI/1ibbnYYQpPL43e1R06XCZ/5piu1byU3ovZYkIPmPnld0MDFLmd4FKbzzgPVIjj/fQpVCsBtZm52JeS437d40MPBuj4r6/Nbsw9CpAxi3wydJgXLyhailHgm1y3Vz2iF5DwGECy3T7mnKK4C4Qf31Q9haNcwhaY9FGEhPVLbHjfDaqyX6zynx1DHduMYZob5wpv134qHmVSJycdeaY/2Yos+oQBx37CDxNt5y2CfsTat+GUNxZOjxnI5eyPqA2TWiBjRpYmv4oNlkb41GZBRE5kETG2qw3Auz/Lu0TkbVXBYL0kEVfuYRPuPvFkFoaDsc30HaN1miQtUIWry2Scv4jMx52a05we1kx04rqwizPjX3MrdCTxgsJi6GKGQ4LBnL7mRy2cjxvkUqZa5oudPfhU4hFd03nDF3AlZZc1haX7hM+5QLvQHAVPH3F3lCZvQ1MzAk3jmMSVFGpyAtKgpzVPza+tJqmbBt/bir5pqig42ZrZ2fYxoNa06Cpnix4fjtnb9IsxFyx1BfLtdUccpGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
