appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GCOCiiWBvqudjPAW8pomlbV3PnyVotiPeCIeztcsjmB0/MjKYLINLGvQpR/6QCfV2Af89l2QA/YBmusfibh3K85uMUHsY5UzAQfCWQ2N/tyT+s5Yw+Ht1/hrXZQvfNbLZtBdkUbyQCFmKetUzJZKslPUw4WhBVE15IpIcBHxuYtvRHmLB6H0Qw4YVEn0pAyfhnETsfVlBkaOnU/WAYeCZM2O9CUuOdwIr007bL/qm7fYNnxrDJnV4dMWykPK0c/pwFAjeYPLWYBj2kihsRA0vzy5D/Ss7T5RCCCwyA3F6gYiJul6ZOEMDw9DqIDO1QonGXyBKRzyZlwT4EnCjMBxVXmOBosU30DbsCIKjERIYfKBazcFzvPh+O3sCh9lHkkkEtV4VBakV2tyBJIR6vs84rjgmM9OxsxsqGP809i5OfxfsN6GuJbS/tkeqinE4cMUC/QswpwxLFAgQRHExgfs/w8ZMFDl2a+Qwtt4JSySykirV6HXla2tIARciEO9WpRgsQbUQE/Xdi4hNOalc6TqUuMyxuXjGcb/gGnOv5H+VSyvjRKYsxg8xkadsNC7G8FLayc40gnaROD4oIKSn1s/k8fsVHQ/77B3Dvo+REjnJAgmmwARz3YItrR2oFBPUMRuRCeppqWgCy1TTnPNwNRDi3S3Um96QUrtqMKAx7e+HCw=}
