travis:
  secure:
    BINSTAR_TOKEN: b4xEqKx4HMZoLX7+QOEyZIM3sI2JNDHqf9Wpq1h6/IzKdVjVJ6135sOG2bfjjscLyWoK/7mRTZhPRNTfBx2RLXg70CkpKZ+mu1iQMcDFuRDPwyMF+Mx3J4qk5RkvX7PG0RxEiuOSziFveTMnxs16Iydex7m1+dVv8YOadWIdUgrN+EDlQIE+aCdBmwoZwfKyNyyf1jP/pvr02cmW3chqMb+J1+qsHnJol63TGRrgEB334f4RXChqdQIRGaKuUaBkl4kLKxlEXfJD2UaSvljpPC7As5FGkZknzkC9n/ch5Ln6gNPVRdEAzeyz85ViNzX/byHJMhPQVGX7EGljt1aZBkU/A1Hqjf6YdNHwyXk94tjjEvtTxb6zjDekeapsqVm1VlqoRDu0qBesHllMfXv8r1HEPsnwzDSBvbnXOaYicWw8phrsZxA/me8Pbt/eWE52PCbazEyCXGwGIyVBDk/Y6s0db/+nnM9kSMr01B58EZi/mok8v6KWmahV1nKrgKo77KLZOwpDGUe+AGlUhhf2qmRPliUWJ2WN9ce086yWXbawP1t+uNkYmC3LqAVPoNQXe7F1MLsoWMuUDVBv8EdjYExuPig6V5j6xxUVWnAxij/rD+6Y3vr2/mJ6BPJToWNObsB/RDGotaxh8Kq3Yl6UK4LLlHfeNtgFI86jg/cfzBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
